# This file is read by BSD make (aka pmake) and redirects making
# things to GNU make which is typically called 'gmake' on systems
# where BSD make is 'make'.

buildtype?=exe
dest?=/usr/local
sudo?=

targets=build \
	clean \
	distclean \
	install \

$(targets) !; @gmake --no-print-directory $@ buildtype=$(buildtype) dest=$(dest) sudo=$(sudo)
