# This file is read by BSD make (aka pmake) and redirects making
# things to GNU make which is typically called 'gmake' on systems
# where BSD make is 'make'.

build?=exe
dest?=/usr/local
sudo?=

targets=all \
	clean \
	distclean \
	install \

$(targets) !; @gmake --no-print-directory $@ build=$(build) dest=$(dest) sudo=$(sudo)
