.PHONY: build plugin clean distclean install

# -*- mode:Makefile -*-

# Makefile fragment used to create per-module Makefiles.
#

ifeq ($(ICI_MODULES_DIR),)
$(error ICI_MODULES_DIR not defined)
endif
ifeq ($(ICI_MODULE_NAME),)
$(error ICI_MODULE_NAME not defined)
endif

# Include Makefile.inc to define common macros.

include $(ICI_MODULES_DIR)/Makefile.inc

# Shorthands for running dmake and install

_dmake = \
	ICI_MODULE_NAME=$(ICI_MODULE_NAME) \
	ICI_DOT_H_DIR=$(ICI_DOT_H_DIR) \
	ICI_LIB_DIR=$(ICI_LIB_DIR) \
	ICI_MACOS_BUNDLE_HOST=$(ICI_MACOS_BUNDLE_HOST) \
	dmake -o $(ICI_PLUGIN_FILE) plugin

_install = $(sudo) install -c -m 444

build: plugin

plugin:; @$(_dmake)

clean:; @$(_dmake) clean

distclean: clean

install: plugin
	@$(_install) $(ICI_PLUGIN_FILE) $(ICI_PLUGIN_DIR)/$(ICI_PLUGIN_FILE)
	@if [ -f $(ICI_PLUGIN_DOT_ICI) ]; then $(_install) $(ICI_PLUGIN_DOT_ICI) $(ICI_PLUGIN_DIR)/$(ICI_PLUGIN_DOT_ICI); fi
