# -*- mode:makefile -*-

.PHONY: all clean

SRCS=   *.c macos/*.c pcre/*.c
OBJS=	$(SRCS:.c=.o)

all:
	@dcc $(SRCS) -o anici &&\
	    ./anici mk-ici-h.ici conf/macos.h

clean:
	rm -rf anici anici.h $(OBJS) .dcc
