/*
 * Any strings listed in this file may be refered to
 * with ICIS(name) for a (string_t *), and ICISO(name) for
 * an (object_t *).
 *
 * This file is included with variying definitions
 * of ICI_STR() to declare, define, and initialise
 * the strings.
 */
ICI_STR(dev, "dev")
ICI_STR(ino, "ino")
ICI_STR(mode, "mode")
ICI_STR(nlink, "nlink")
ICI_STR(uid, "uid")
ICI_STR(gid, "gid")
ICI_STR(rdev, "rdev")
ICI_STR(size, "size")
ICI_STR(atime, "atime")
ICI_STR(mtime, "mtime")
ICI_STR(ctime, "ctime")
ICI_STR(blksize, "blksize")
ICI_STR(blocks, "blocks")
ICI_STR(name, "name")
ICI_STR(passwd, "passwd")
ICI_STR(gecos, "gecos")
ICI_STR(dir, "dir")
ICI_STR(shell, "shell")
ICI_STR(dupfd, "dupfd")
ICI_STR(getfd, "getfd")
ICI_STR(setfd, "setfd")
ICI_STR(getfl, "getfl")
ICI_STR(setfl, "setfl")
ICI_STR(getown, "getown")
ICI_STR(setown, "setown")
ICI_STR(setlk, "setlk")
ICI_STR(sec, "sec")
ICI_STR(usec, "usec")
ICI_STR(infinity, "infinity")
ICI_STR(real, "real")
ICI_STR(virtual, "virtual")
ICI_STR(prof, "prof")
ICI_STR(interval, "interval")
ICI_STR(value, "value")
ICI_STR(start, "start")
ICI_STR(len, "len")
ICI_STR(pid, "pid")
ICI_STR(type, "type")
ICI_STR(whence, "whence")
ICI_STR(rdlck, "rdlck")
ICI_STR(wrlck, "wrlck")
ICI_STR(unlck, "unlck")
ICI_STR(core, "core")
ICI_STR(cpu, "cpu")
ICI_STR(data, "data")
ICI_STR(fsize, "fsize")
ICI_STR(memlock, "memlock")
ICI_STR(nofile, "nofile")
ICI_STR(nproc, "nproc")
ICI_STR(rss, "rss")
ICI_STR(stack, "stack")
ICI_STR(sbsize, "sbsize")
ICI_STR(cur, "cur")
ICI_STR(max, "max")
ICI_STR(infinity, "infinity")
ICI_STR(status, "status")
