.TH iciHTTP 1 "The ICI Programming Language" "" "The ICI Programming Language"
.SH "NAME"
iciHTTP - The ICI HTTP module
.SH "DESCRIPTION"
.P
A module for performing HTTP requests.
.P
.RS 5
.nf

.fi
.RE 1
.SH "DETAILS"
.SS "HTTP.Request"
.P
Class representing an HTTP request.
.P
.RS 5
.nf

.fi
.RE 1
.SS "HTTP.Request:set_default_proxy(host, port)"
.P
Class method to set the proxy host and port used by
default by all new request instances.
.SH "SEE ALSO"
ici(1), iciex(1)
