.TH icicfunc 1 "The ICI Programming Language" "" "The ICI Programming Language"
.SH "NAME"
icicfunc - The ICI cfunc module - Embedded native-code extension functions
.SH "DESCRIPTION"
.P
The ICI cfunc module provides a facility for embedding
native code extension functions within ICI source files.
The cfunc module defines a "[cfunc ...]" literal which
contains the C source code for native-code ICI functions.
The cfunc module provides a parser extension function
which extracts this code, wraps it in an ICI native-code
module structure and then calls the system C compiler
to build a dynamically loadable ICI module from the
resultant C source file. The function, in its native-code
ICI module form, is then dynamically loaded into the
ICI process.
.P
The "[cfunc ... ]" literal has the following form:
.P
.RS 5
.nf
\'[cfunc\' c-identifier c-function-body \']\'
.fi
.RE 1
.P
The c-identifier defines the name by which the extension
function may be referenced from within the ICI program.
The c-function-body is the complete C source code for
the extension function. E.g., the following defines
a native code function that adds two, ICI, integers
(which ICI represents using C\'s long int type).
.P
.RS 5
.nf
[cfunc add_two_integers
{
    long a, b;
    if (ici_typecheck("ii", &a, &b))
        return 1;
    return ici_int_ret(a + b);
}]
.fi
.RE 1
.P
When the above code is encountered during parsing of
the ICI program the function body is extracted and
written to a temporary file which is then compiled
and an appropriate dynamic library constructed from
its object file. The dynamic library is then loaded
using ICI\'s dynamic loading function, load().
.P
To avoid re-compilation a hash of the source code file
is maintained alongside the dynamic library file. If
the newly extracted source code has an identical hash
value to any existing hash then the module is used
as is. Note that because comments are stripped from
the embedded source code simple changes in commentary
will not result in re-compilation.
.SH "SEE ALSO"
ici(1), iciex(1)
